# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/jpeg_z7_asic_8x8.cache/wt [current_project]
set_property parent.project_path F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/jpeg_z7_asic_8x8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_output_repo f:/jpeg_encoder/asic/jpeg_z7_asic_8x8/jpeg_z7_asic_8x8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/ac_lut.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/booth_algo.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/conc_bytes.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/dc_lut.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/dct_lut.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/dot_pro.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/en_magn.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/encoder.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/fdct.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/fixed_div_nb.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/fixed_mul_nb.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/float_add_nb.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/float_div_nb.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/float_mul_nb.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/float_to_int8.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/int8_to_float.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/lead_nz.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/level_shift.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/mcu_8x8.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/qnt.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/ram_8bx64.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/ram_8bx8.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/rle.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/shift_reg.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/zigzag.sv
  F:/jpeg_encoder/asic/jpeg_z7_asic_8x8/src/jpeg.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top jpeg -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef jpeg.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file jpeg_utilization_synth.rpt -pb jpeg_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
